<?php 
/**
 * Template for index action
 * 
 * @category   OntoWiki
 * @package    OntoWiki_extensions_patapro
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<script type="text/javascript">       
    var url = '<?php echo $this->url; ?>';
    var models = <?php echo json_encode($this->models); ?>;
</script>

<!-- set the title of the action -->
<?php $this->placeholder('main.window.title')->set($this->_translate->_('ontologieEdit')); ?>
<br />
<table id="storeTable">
    <tr>
        <td class="storeModelNameTd">
            <?php echo $this->_translate->_('backupQuestion') ?>
        </td>
        <td class="storeModelStatusTd">
            <div class="onoffswitch">
                <input type="checkbox" name="backup" class="onoffswitch-checkbox" id="storeBackup" value="true" checked="checked">
                <label class="onoffswitch-label" for="storeBackup">
                    <div class="onoffswitch-inner"></div>
                    <div class="onoffswitch-switch"></div>
                </label>
            </div>
        </td>
		<td class="storeModelHiddenTd">
        </td>
        <td class="storeModelButtonTd">
        </td>
        <td>
        </td>
    </tr>
    <tr><td><br /></td></tr>
    <tr>
        <th class="storeModelNameTd"></th>
        <th class="storeModelStatusTd"><?php echo $this->_translate->_('status') . "" ?></th>
        <th class="storeModelHiddenTd"><?php echo $this->_translate->_('hidden') . "" ?></th>
        <th class="storeModelButtonTd"></th>
        <th class="storeModelProcessTd"></th>
    </tr>
	<tr>
		<td class="storeModelNameTd">
            <span class="storeModelNameSpan">All</span>
        </td>
        <td class="storeModelStatusTd">
        </td>
		<td class="storeModelHiddenTd">
        </td>
        <td class="storeModelButtonTd">
            <a id="allCreate" class="button" onclick="javascript:renewAllModel('create')" title="<?php echo $this->_translate->_('createKB') ?>">
                <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/createKB.png" alt="<?php echo $this->_translate->_('createKB') ?>">
            </a>
            <a id="allFill" class="button" onclick="javascript:renewAllModel('fill')" title="<?php echo $this->_translate->_('fillKB') ?>">
                <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/fillKB.png" alt="<?php echo $this->_translate->_('fillKB') ?>">
            </a>
            <a id="allAdd" class="button" onclick="javascript:renewAllModel('add')" title="<?php echo $this->_translate->_('addKB') ?>">
                <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/addKB.png" alt="<?php echo $this->_translate->_('addKB') ?>">
            </a>
            <a id="allRenew" class="button" onclick="javascript:renewAllModel('renew')" title="<?php echo $this->_translate->_('renewKB') ?>">
                <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/renewKB.png" alt="<?php echo $this->_translate->_('renewKB') ?>">
            </a>
            <a id="allClear" class="button" onclick="javascript:renewAllModel('clear')" alt="<?php echo $this->_translate->_('clearKB') ?>">
                <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/clearKB.png" title="<?php echo $this->_translate->_('clearKB') ?>">
            </a>
            <a id="allDelete" class="button" onclick="javascript:renewAllModel('delete')" alt="<?php echo $this->_translate->_('deleteKB') ?>">
                <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/deleteKB.png" title="<?php echo $this->_translate->_('deleteKB') ?>">
            </a>
            <a id="allBackup" class="button" onclick="javascript:renewAllModel('backup')" alt="<?php echo $this->_translate->_('backupKB') ?>">
                <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/backupKB.png" title="<?php echo $this->_translate->_('backupKB') ?>">
            </a>
        </td>
        <td class="storeModelProcessTd">
            <div id="responseAll"></div>
        </td>
	</tr>
	<?php foreach($this->models as $modelName => $modelData) { ?>
        <tr>
            <?php if ('namespaces' != $modelName) { ?>
                <td class="storeModelNameTd" title="<?php echo $modelData['namespace'] ?>">
                    <span class="storeModelNameSpan"><?php echo $modelName; ?></span>
                </td>
                <td class="storeModelStatusTd">
                    <?php
                        $availableClass = "storeHidden ";
                        $notAvailableClass = "";
                        if (isset($this->storedModels[$modelData['namespace']])) {
                            $availableClass = "";
                            $notAvailableClass = "storeHidden ";
                        }
                    ?>
                    <div id="model<?php echo $modelName ?>StatusA" class="<?php echo $availableClass ?>storeModelAvailable"><?php echo $this->_translate->_('available') . "" ?></div>
                    <div id="model<?php echo $modelName ?>StatusNA" class="<?php echo $notAvailableClass ?>storeModelNotAvailable"><?php echo $this->_translate->_('notavailable') . "" ?></div>
                </td>
                <td class="storeModelHiddenTd">
                    <?php
                        $hiddenDefault = '';
                        if (isset($modelData['options'])) {
                            $hiddenDefault = (in_array('hidden', $modelData['options']) ? 'checked="checked"' : '');
                        }
                        ?>
                    <div class="onoffswitch">
                        <input type="checkbox" name="hidden" class="onoffswitch-checkbox" id="model<?php echo $modelName ?>Hidden" value="true" <?php echo $hiddenDefault ?>>
                        <label class="onoffswitch-label" for="model<?php echo $modelName ?>Hidden">
                            <div class="onoffswitch-inner"></div>
                            <div class="onoffswitch-switch"></div>
                        </label>
                    </div>
                </td>
                <td class="storeModelButtonTd">
                    <?php
                        if (isset($this->storedModels[$modelData['namespace']])) {
                            $hiddenAddClass = " storeDisabledButton ";
                            $hiddenRemoveClass = "";
                        } else {
                            $hiddenAddClass = "";
                            $hiddenRemoveClass = " storeDisabledButton ";
                        }
                    ?>
                    <a id="model<?php echo $modelName ?>Create" class="button <?php echo $hiddenAddClass ?>" onclick="javascript:renewModel('<?php echo $modelName; ?>', 'create')" title="<?php echo $this->_translate->_('createKB') ?>">
                        <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/createKB.png" alt="<?php echo $this->_translate->_('createKB') ?>">
                    </a>
                    <a id="model<?php echo $modelName ?>Fill" class="button <?php echo $hiddenRemoveClass ?>" onclick="javascript:renewModel('<?php echo $modelName; ?>', 'fill')" title="<?php echo $this->_translate->_('fillKB') ?>">
                        <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/fillKB.png" alt="<?php echo $this->_translate->_('fillKB') ?>">
                    </a>
                    <a id="model<?php echo $modelName ?>Add" class="button <?php echo $hiddenAddClass ?>" onclick="javascript:renewModel('<?php echo $modelName; ?>', 'add')" title="<?php echo $this->_translate->_('addKB') ?>">
                        <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/addKB.png" alt="<?php echo $this->_translate->_('addKB') ?>">
                    </a>
                    <a id="model<?php echo $modelName ?>Renew" class="button <?php echo $hiddenRemoveClass ?>" onclick="javascript:renewModel('<?php echo $modelName; ?>', 'renew')" title="<?php echo $this->_translate->_('renewKB') ?>">
                        <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/renewKB.png" alt="<?php echo $this->_translate->_('renewKB') ?>">
                    </a>
                    <a id="model<?php echo $modelName ?>Clear" class="<?php echo $hiddenRemoveClass ?>button" onclick="javascript:renewModel('<?php echo $modelName; ?>', 'clear')" title="<?php echo $this->_translate->_('clearKB') ?>">
                        <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/clearKB.png" alt="<?php echo $this->_translate->_('clearKB') ?>">
                    </a>
                    <a id="model<?php echo $modelName ?>Delete" class="<?php echo $hiddenRemoveClass ?>button" onclick="javascript:renewModel('<?php echo $modelName; ?>', 'delete')" title="<?php echo $this->_translate->_('deleteKB') ?>">
                        <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/deleteKB.png" alt="<?php echo $this->_translate->_('deleteKB') ?>">
                    </a>
                    <a id="model<?php echo $modelName ?>Backup" class="<?php echo $hiddenRemoveClass ?>button" onclick="javascript:renewModel('<?php echo $modelName; ?>', 'backup')" title="<?php echo $this->_translate->_('backupKB') ?>">
                        <img src="<?php echo $this->url; ?>/extensions/kbmanager/public/img/backupKB.png" alt="<?php echo $this->_translate->_('backupKB') ?>">
                    </a>
                </td>
                <td class="storeModelProcessTd">
                    <div id="response<?php echo $modelName; ?>"></div>
                </td>
            <?php } ?>
        </tr>
	<?php } ?>
    <tr>
        <td class="storeModelNameTd">
            <span class="storeModelNameSpan">Log</span>
        </td>
        <td></td>
        <td></td>
        <td class="storeModelButtonTd">
            <textarea id="storeModelProcessArea"></textarea>
        </td>
    </tr>
</table>


